os: osx
language: shell

osx_image: xcode11.3

before_script:
  - chmod +x gradlew
  - chmod +x travis_script.sh

script: ./travis_script.sh

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/
    - /var/root/.gradle/caches
    - /var/root/.gradle/wrapper
    - /var/root/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true