os: osx
language: shell

osx_image: xcode11

before_install:
  - chmod +x gradlew

script: ./gradlew build --parallel

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true