language: objective-c

os: osx

osx_image: xcode11.2

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true