os: osx
language: shell

osx_image: xcode11.3

before_script:
  - chmod +x gradlew
  - chmod +x travis_script.sh

env:
  - TO_BUILD="core, core-static"
  - TO_BUILD="auth, auth-static"
  - TO_BUILD="storage, storage-static"
  - TO_BUILD="firestore, firestore-static"
  - TO_BUILD="database, database-static"
  - TO_BUILD="dynamicLinks, dynamicLinks-static"
  - TO_BUILD="functions, functions-static"
  - TO_BUILD="messaging, messaging-static"

script: ./travis_script.sh

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.konan/

deploy:
  provider: script
  script: ./gradlew bintrayUpload -Dorg.gradle.console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true